remote_theme: just-the-docs/just-the-docs
title: VerifyMarxisme Docs
description: Documentation pour le bot Discord VerifyMarxisme
baseurl: "/verifymarxisme"
url: "https://USERNAME.github.io"

# Personnalisation du thème
color_scheme: dark
search_enabled: true
heading_anchors: true

# Configuration de la navigation
aux_links:
  "GitHub Repository":
    - "//github.com/USERNAME/verifymarxisme"

# Personnalisation des couleurs
colors:
  brand: "#FF0000"
  sidebar: "#1a1a1a"
  nav: "#2a2a2a"

# Footer
footer_content: "Copyright &copy; 2025 VerifyMarxisme. Distribué sous licence MIT."
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"
